production:
  all:
    console:
      opt1: true
  test:
    console:
      opt1: true
      format: '%d %h:%l %c- %m'
  test.subtest:
    error:
      - console:
          opt1: true
          format:
            name: 'default'
            value: '%d %h:%l %c- %m'
      - console:
          opt1: true
          format:
            name: 'default'
            value: '%d %c %m'
  test.subtest.subtest:
    console:
      opt1: true
      format: '%d %h:%l %c- %m'
development:
  $extends: production