default:
  $inner: false
  all:
    file:
      fileName: 'test.log'
      encoding: 'UTF8'
    console:
      opt1: true
production:
  $extends: default
  test:
    console:
      opt1: true
  test.subtest:
    error:
      - console:
          opt1: true
      - console:
          opt1: true
  test.subtest.subtest:
    console:
      opt1: true
    console:
      $extends: :$config.mongo
development:
  $extends: production
$config:
  default.format.processor: 'default'
  default.format.value: '%level %date: %hostname %module(%label) %message \n\nTrace:\n %trace \n\n Arg1:\n %args[0](10) \n\n Args(10):\n %args(10) \n\n Args:\n %args \n\n Errors:\n %errors \n\nCode: \n %code'
  mongo:
    uri: 'mongodb://'