default:
  $inner: false
  all:
    file:
      fileName: 'test.log'
      encoding: 'ASCII'
    console:
      opt1: true
production:
  $extends: default
  test:
    console:
      opt1: true
  test.subtest:
    error:
      - console:
          opt1: true
      - console:
          opt1: true
  test.subtest.subtest:
    console:
      opt1: true
    console:
      $extends: :$config.mongo
development:
  $extends: production
$config:
  default.format.processor: 'default'
  default.format.value: '%date %hostname %message'
  mongo:
    uri: 'mongodb://'