$config:
  default.format.processor: 'default'
  default.format.value: '%level %date: %hostname %module(%label) %message \n\nTrace:\n %trace \n\n Arg1:\n %args[0](10) \n\n Args(10):\n %args(10) \n\n Args:\n %args \n\n Errors:\n %errors \n\nCode: \n %code'
  mongo:
    uri: 'mongodb://localhost/the-logger'
    ttl: 3600
    format:
      name: 'default'
      value: '%level, %date, %module, %hostname, %args, %code, %trace, %errors, %stack'
  fluentd:
    tag: 'ru.realweb.redfog.dsp'
    host: 'logging.vmc.loc'
    port: 24224
    timeout: 5
    verbose: true
default:
  all:
    - file:
        fileName: 'test.log'
        encoding: 'UTF8'
      console: false
    - syslog: true
  test.mongo:
    info,debug:
#      console: false
      mongo:
       $extend: :$config.mongo
       ttl: 10

    error:
      - mongo:
          $extend: :$config.mongo
          ttl: 100
      - console: false
  test.fluentd:
    info,debug,error,fatal:
      fluentd:
        $extend: :$config.fluentd

