production:
  all:
    console: true
  test:
    console:
      format: '%d %h:%l %c- %m'
  test.subtest:
    error:
      - console:
          format:
            name: 'default'
            value: '%d %h:%l %c- %m'
      - console:
              format:
                name: 'default'
                value: '%d %c %m'
  test.subtest.subtest:
    console:
      format: '%d %h:%l %c- %m'
development:
  $extends: production